University Management System/UMSMVC5/Models/CourseAssign.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace UMSMVC5.Models
{
    public class CourseAssign
    {
        [Key]
        public int CourseAssignId { get; set; }

        public int CourseId { get; set; }

        public int TeacherId { get; set; }

        [ForeignKey("CourseId")]
        public virtual Course Course  { get; set; }

        [ForeignKey("TeacherId")]
        public virtual Teacher Teacher { get; set; }
    }
}

University Management System/UMSMVC5/Controllers/CourseAssignController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UMSMVC5.Models;
using UMSMVC5.Notifications;

namespace UMSMVC5.Controllers
{
    public class CourseAssignController : Controller
    {
        private UMSMVC5DbContext db = new UMSMVC5DbContext();

        // GET: /CourseAssign/
        public ActionResult Index()
        {
            var courseassigns = db.CourseAssigns.Include(c => c.Course).Include(c => c.Teacher);
            return View(courseassigns.ToList());
        }


        public ViewResult ViewCourseStatus(int? departmentID)
        {
            ViewBag.DepartmentID = new SelectList(db.Departments, "DepartmentId", "DepartmentCode");

            var courselist = new List<Course>();
            if (departmentID != null)
            {
                courselist = db.Courses.Include(c => c.Semester).Where(c => c.DepartmentId == departmentID).ToList();
            }
            else
            {
                courselist = db.Courses.Include(c => c.Semester).ToList();
            }

            //var coursedbset = db.Courses.Include(c => c.Department).Include(c => c.Semester);
            return View(courselist.ToList());
        }

        public PartialViewResult CourseFilter(int? departmentID)
        {
            var courselist=new List<Course>();
            if (departmentID != null)
            {
                courselist = db.Courses.Include(c => c.Semester).Where(c => c.DepartmentId == departmentID).ToList();
            }
            else
            {
                courselist = db.Courses.Include(c => c.Semester).ToList();
            }
            return PartialView("~/Views/CourseAssign/_CourseFilter.cshtml", courselist);
        }


        public JsonResult GetDepartmentList()
        {

            db.Configuration.ProxyCreationEnabled = false;

            var departmentlist = db.Departments.ToList();

            return Json(departmentlist, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetTeacherList(int? DepartmentId)
        {

            db.Configuration.ProxyCreationEnabled = false;

            var teacherlist = db.Teachers.Where(t=>t.DepartmentId==DepartmentId);

            return Json(teacherlist.ToList(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCourseList(int? DepartmentId)
        {

            db.Configuration.ProxyCreationEnabled = false;

            var courseList = db.Courses.Where(t => t.DepartmentId == DepartmentId);

            return Json(courseList.ToList(), JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult GetTeacherCreditInfo(int? teacherId)
        {
            var aTeacher = new Teacher();
            if (teacherId != null)
            {
                aTeacher = db.Teachers.Where(t => t.TeacherId == teacherId).FirstOrDefault();
            }
            return PartialView("~/Views/CourseAssign/_TeacherCreditInfo.cshtml", aTeacher);
        }

        public PartialViewResult GetCourseInfo(int? courseId)
        {
            var aCourse = new Course();
            if (courseId != null)
            {
                aCourse = db.Courses.Where(c => c.CourseId == courseId).FirstOrDefault();
            }
            return PartialView("~/Views/CourseAssign/_CourseInfor.cshtml", aCourse);
        }


        // GET: /CourseAssign/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CourseAssign courseassign = db.CourseAssigns.Find(id);
            if (courseassign == null)
            {
                return HttpNotFound();
            }
            return View(courseassign);
        }

        // GET: /CourseAssign/Create
        public ActionResult Create()
        {
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseCode");
            ViewBag.TeacherId = new SelectList(db.Teachers, "TeacherId", "TeacherName");
            return View();
        }

        // POST: /CourseAssign/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="CourseAssignId,CourseId,TeacherId")] CourseAssign courseassign)
        {
            if (ModelState.IsValid)
            {
                CourseAssign acCourseAssign = db.CourseAssigns.FirstOrDefault(ca => ca.CourseId == courseassign.CourseId);
                Course aCourse = db.Courses.FirstOrDefault(c => c.CourseId == courseassign.CourseId);
                Teacher aTeacher = db.Teachers.FirstOrDefault(t => t.TeacherId == courseassign.TeacherId);

                if (acCourseAssign != null)
                {

                    Teacher assignTeacher = db.Teachers.FirstOrDefault(ast => ast.TeacherId == acCourseAssign.TeacherId);
                    if (assignTeacher != null)
                    {
                        if (aCourse != null)
                        {

                            this.ShowMessage(MessageType.Error, "This Course : " + aCourse.CourseCode + " has already been assaigned to " + assignTeacher.TeacherName, true);
                          
                            ViewBag.CourseId = new SelectList(db.Courses.Where(c => c.CourseId == aCourse.CourseId), "CourseId", "CourseCode");
                            ViewBag.TeacherId = new SelectList(db.Teachers.Where(t => t.TeacherId == aTeacher.TeacherId), "TeacherId", "TeacherName");

                            return View();
                        }
                    }
                }

                aTeacher.CreditsHaveTaken += aCourse.CourseCredit;
                aTeacher.CreditsRemaining -= aCourse.CourseCredit;
                db.CourseAssigns.Add(courseassign);
                aCourse.AssignCourse = aTeacher.TeacherName;
              
                int save =db.SaveChanges();
                if (save > 0)
                {
                    this.ShowMessage(MessageType.Success, "This Course" +aCourse.CourseCode
                        + " has been assigned to Teacher :- " + aTeacher.TeacherName
                        + " successfully .", true);

                    return RedirectToAction("Index");
                }
                return RedirectToAction("Index");
            }

            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseCode", courseassign.CourseId);
            ViewBag.TeacherId = new SelectList(db.Teachers, "TeacherId", "TeacherName", courseassign.TeacherId);
            return View(courseassign);
        }

        // GET: /CourseAssign/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CourseAssign courseassign = db.CourseAssigns.Find(id);
            if (courseassign == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseCode", courseassign.CourseId);
            ViewBag.TeacherId = new SelectList(db.Teachers, "TeacherId", "TeacherName", courseassign.TeacherId);
            return View(courseassign);
        }

        // POST: /CourseAssign/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="CourseAssignId,CourseId,TeacherId")] CourseAssign courseassign)
        {
            if (ModelState.IsValid)
            {
                db.Entry(courseassign).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseCode", courseassign.CourseId);
            ViewBag.TeacherId = new SelectList(db.Teachers, "TeacherId", "TeacherName", courseassign.TeacherId);
            return View(courseassign);
        }

        // GET: /CourseAssign/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CourseAssign courseassign = db.CourseAssigns.Find(id);
            if (courseassign == null)
            {
                return HttpNotFound();
            }
            return View(courseassign);
        }

        // POST: /CourseAssign/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CourseAssign courseassign = db.CourseAssigns.Find(id);
            db.CourseAssigns.Remove(courseassign);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

University Management System/UMSMVC5/Views/CourseAssign/Create.cshtml
@model  UMSMVC5.Models.CourseAssign

@{
    ViewBag.Title = "Create";
}

<style>

    #Teacher-Data {
        display: none;
    }

    #Course-Data {
        display: none;
    }

   .success {
        background-color: #a7d4f5;
        color: #fff;
        height: 20px;
        font-family: Arial;
        font-weight: bold;
        font-size: 16px;
        padding: 5px;
        text-align: center;
        display: none;
    }

    .main {
        width: 600px;
        background-color: #f8f8f8;
        margin: 0px auto;
        padding: 10px;
    }

    #partialview {
        background-color: #e8f1f7;
        color: #000000;
        position: relative;
    }

  

</style>

<h2>Create</h2>


@using (Html.BeginForm("Create", "CourseAssign", FormMethod.Post, new { id = "ajaxform" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CourseAssign</h4>
        <hr />
        @Html.ValidationSummary(true)
        
        <div class="form-group">
            <label class="control-label col-md-2">Department</label>
            <div class="col-md-10">
                <select id="DepartmentId" name="DepartmentId" class="form-control" data-val-required="'Department must not be empty." data-val="true"></select>
               
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-md-2">Teacher</label>
            <div class="col-md-10">
                <select id="TeacherId" name="TeacherId" class="form-control" data-val-required="'Teacher must not be empty." data-val="true"></select>
                @Html.ValidationMessageFor(model => model.TeacherId)
            </div>
        </div>
        
        <div class="form-group">
           
            <div class="col-md-10 col-md-offset-2">
                <div id="Teacher-Data">

                </div>

            </div>
        </div>
        
       
        
        <div class="form-group">
            <label class="control-label col-md-2">Course</label>
            <div class="col-md-10">
                <select id="CourseId" name="CourseId" class="form-control" data-val-required="'Course must not be empty." data-val="true"></select>
                @Html.ValidationMessageFor(model => model.CourseId)
             </div>
        </div>
        
        <div class="form-group">

            <div class="col-md-10 col-md-offset-2">
                <div id="Course-Data">

                </div>

            </div>
        </div>

      

        @*<div class="form-group">
            @Html.LabelFor(model => model.CourseId, "CourseId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseId", String.Empty)
                @Html.ValidationMessageFor(model => model.CourseId)
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.TeacherId, "TeacherId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TeacherId", String.Empty)
                @Html.ValidationMessageFor(model => model.TeacherId)
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
                @*<input type="button" id="submit" value="Create" class="btn btn-default" />*@
            </div>
        </div>
    </div>
}


<div id="progressDialog" style="display: none;">
    @*<img src="~/Image/ajax-loader.gif" />*@
    Please Wait ....
</div>

<div class="success">Saved</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    
    
    <script type="text/javascript">
        
        $(function () {
            

            $.getJSON("/CourseAssign/GetDepartmentList", function (data) {
                var items = "<option></option>";
                $.each(data, function (i, GetDepartmentList) {
                    items += "<option value='" + GetDepartmentList.DepartmentId + "'>" + GetDepartmentList.DepartmentCode + "</option>";
                });
                $("#DepartmentId").html(items);
            });
        
            $("#DepartmentId").change(function () {

                Clear();
            
                var id = $("#DepartmentId").val();
                if (id > 0) {
                    var Param = { DepartmentId: $("#DepartmentId > option:selected").attr("value") };
                    $.getJSON("/CourseAssign/GetTeacherList/", Param, function (data) {
                        var items = "<option></option>";
                        $.each(data, function (i, GetTeacherList) {
                            items += "<option value='" + GetTeacherList.TeacherId + "'>" + GetTeacherList.TeacherName + "</option>";
                        });
                        $("#TeacherId").html(items);
                    });
                
                    $.getJSON("/CourseAssign/GetCourseList/", Param, function (data) {
                        var items = "<option></option>";
                        $.each(data, function (i, GetCourseList) {
                            items += "<option value='" + GetCourseList.CourseId + "'>" + GetCourseList.CourseCode + "</option>";
                        });
                        $("#CourseId").html(items);
                    });

                }
                else {

                    Clear();
                }
        
           
            });
        
        
        
            $("#TeacherId").change(function () {
                var id = $("#TeacherId").val();
                if (id>0) {
                    $("#Teacher-Data").load("/CourseAssign/GetTeacherCreditInfo", { TeacherId: id }).show();
                } else {
                    $("#Teacher-Data").hide();
                }
           
            });
        
            $("#CourseId").change(function () {
                var id = $("#CourseId").val();
                if (id > 0) {
                    $("#Course-Data").load("/CourseAssign/GetCourseInfo", { CourseId: id }).show();
                } else {
                    $("#Course-Data").hide();
                }

            });

            function Clear() {
            
                $("#Teacher-Data").hide();
                $("#Course-Data").hide();
                $('#TeacherId').find('option').remove();
                $('#CourseId').find('option').remove();
            };
        





        });

    </script>
    
    
    
    
    @*<script>

        $(function() {
         
            $("#submit").click(function () {
                

                var t = $("#TeacherId").val();
                var c = $("#CourseId").val();
                alert(t);
                alert(c);

                if ($('#ajaxform').valid()) {
                    $.ajax({
                        url: "../CourseAssign/Create",
                        type: "POST",
                        //datatype: "json",
                        contentType: 'application/json; charset=utf-8',
                        async: true,
                        data: {
                            TeacherId: t,
                            CourseId: c

                        },
                        beforeSend: function () {
                            $("#progressDialog").show();
                        },
                        complete: function () {
                            $("#progressDialog").hide();
                        },
                        success: function (result) {
                            $(".success").slideDown(300).delay(800).slideUp(300);
                            //$("#partialview").html(result);

                        },
                        error: function () {
                          
                            alert("Try Again");
                        }

                    });
                }
            });


        });



    </script>*@

}

University Management System/UMSMVC5/Views/CourseAssign/Delete.cshtml
@model UMSMVC5.Models.CourseAssign

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CourseAssign</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course.CourseCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.CourseCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Teacher.TeacherName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Teacher.TeacherName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

University Management System/UMSMVC5/Views/CourseAssign/Details.cshtml
@model UMSMVC5.Models.CourseAssign

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>CourseAssign</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course.CourseCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.CourseCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Teacher.TeacherName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Teacher.TeacherName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CourseAssignId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

University Management System/UMSMVC5/Views/CourseAssign/Edit.cshtml
@model UMSMVC5.Models.CourseAssign

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CourseAssign</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.CourseAssignId)

        <div class="form-group">
            @Html.LabelFor(model => model.CourseId, "CourseId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseId", String.Empty)
                @Html.ValidationMessageFor(model => model.CourseId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TeacherId, "TeacherId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TeacherId", String.Empty)
                @Html.ValidationMessageFor(model => model.TeacherId)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

University Management System/UMSMVC5/Views/CourseAssign/Index.cshtml
@using UMSMVC5.Helpers
@model IEnumerable<UMSMVC5.Models.CourseAssign>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Course.CourseCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Teacher.TeacherName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Course.CourseCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Teacher.TeacherName)
        </td>
        <td>
            
            @Html.NoEncodeActionLink("<span class='glyphicon glyphicon-pencil'></span>", "Edit", "Edit", "CourseAssign", routeValues: new { id = item.CourseAssignId }, htmlAttributes: new { data_modal = "", @class = "btn btn-default" })
@Html.NoEncodeActionLink("<span class='glyphicon glyphicon-tasks'></span>", "Details", "Details", "CourseAssign", routeValues: new { id = item.CourseAssignId }, htmlAttributes: new { data_modal = "", @class = "btn btn-default" })
@Html.NoEncodeActionLink("<span class='glyphicon glyphicon-trash'></span>", "Delete", "Delete", "CourseAssign", routeValues: new { id = item.CourseAssignId }, htmlAttributes: new { data_modal = "", @class = "btn btn-danger" })

            @*@Html.ActionLink("Edit", "Edit", new { id=item.CourseAssignId }) |
            @Html.ActionLink("Details", "Details", new { id=item.CourseAssignId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CourseAssignId })*@
        </td>
    </tr>
}

</table>

University Management System/UMSMVC5/Views/CourseAssign/ViewCourseStatus.cshtml
@model IEnumerable<UMSMVC5.Models.Course>

@{
    ViewBag.Title = "ViewCourseStatus";
}


<h2>View Course Status </h2>

@using (Html.BeginForm())
{
    <div>
        <h2>Select Department </h2>
        @Html.DropDownList("DepartmentId", String.Empty)
    </div>
}

<br />

<div id="course-data">
    @Html.Partial("~/Views/CourseAssign/_CourseFilter.cshtml", Model)
</div>


@section Scripts {

    <script type="text/javascript">
        @*function FillData(id) {
            $('#course-data').load('@Url.Action("CourseFilter")', { departmentID: id });
        }

        $(function() {
            $('#DepartmentId').change(function() {
                var id = $('#DepartmentId').val();
                FillData(id);
            });
        });*@
        
        $(function () {
            $("#DepartmentId").change(function () {
                var id = $("#DepartmentId").val();
                $("#course-data").load("/CourseAssign/CourseFilter", { departmentID: id });
            });
        });

    </script>

}

University Management System/UMSMVC5/Views/CourseAssign/_CourseFilter.cshtml
@model IEnumerable<UMSMVC5.Models.Course>

<table class="table">
    <tr>
        <th>
            Course Code
        </th>
        <th>
           Course Name
        </th>
        <th>
            Semester
        </th>
        <th>
            Assigned To
        </th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CourseCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourseTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Semester.SemesterName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AssignCourse)
            </td>

        </tr>
    }

</table>

University Management System/UMSMVC5/Views/CourseAssign/_CourseInfor.cshtml
@model UMSMVC5.Models.Course

<p>@Html.DisplayNameFor(model => model.CourseTitle)  : @Model.CourseTitle</p>

<p>@Html.DisplayNameFor(model => model.CourseCredit)  : @Model.CourseCredit</p>

University Management System/UMSMVC5/Views/CourseAssign/_TeacherCreditInfo.cshtml
@model UMSMVC5.Models.Teacher



<p>@Html.DisplayNameFor(model => model.CreditsToBeTaken)  : @Model.CreditsToBeTaken</p>

<p>@Html.DisplayNameFor(model => model.CreditsHaveTaken)  : @Model.CreditsHaveTaken</p>

<p>@Html.DisplayNameFor(model => model.CreditsRemaining)  : @Model.CreditsRemaining</p>